server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;

    location / {
        index index.html;
        # always re-fetch index.html
        add_header Cache-Control "no-cache, no-store, must-revalidate" always;
    }

    location ~* \.(?:js|css|svg|png|jpg|jpeg|gif|woff2?)$ {
        # aggressively cache static assets
        add_header Cache-Control "public, max-age=31536000, immutable" always;
    }
}
