server {
    listen 80;
    listen [::]:80;

    server_name localhost;

    root /usr/share/nginx/html;
    port_in_redirect off;

    location ~ \.css {
		add_header  Content-Type text/css;
	}
	location ~ \.js {
		add_header  Content-Type application/x-javascript;
	}

    location / {
        root /usr/share/nginx/html;
        index  index.html index.htm;
    }

    location ^~ /sample-frontend {
        alias /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
        include /etc/nginx/mime.types;
    }
}
